name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag healthtrack-fitness-tracker:latest

    - name: Run Django tests in Docker
      run: docker run --rm healthtrack-fitness-tracker:latest python manage.py test


  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag healthtrack-fitness-tracker:$(date +%s)